POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "midnight.a": "dev666",
  "midnight.b": "bbb666"
}

###
GET http://localhost:9129/list?app=app1&env=dev&ns=public
Accept: application/json

<> 2024-05-06T210917.200.json

###
GET http://localhost:8888/demo
Accept: application/json


###
GET http://localhost:9130/status
Accept: application/json
